--- 
author: "Matt Carroll <fluttery.io@gmail.com>"
dependencies: 
  flutter: 
    sdk: flutter
description: "Flutter package that helps with prototyping."
dev_dependencies: 
  test: ^0.12.0
environment: 
  sdk: ">=1.24.3 <3.0.0"
homepage: "https://github.com/matthew-carroll/fluttery"
name: fluttery
version: "0.0.7"
